---
- name: Discover device facts
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Gather hardware and interface facts for IOS/IOS-XE
      cisco.ios.ios_facts:
        gather_subset:
          - hardware
          - interfaces
      when: "'IOS-XE' in group_names[0]"

    - name: Gather hardware and interface facts for NX-OS
      cisco.nxos.nxos_facts:
        gather_subset:
          - hardware
          - interfaces
      when: "'NX-OS' in group_names[0]"